/* Generated by tools/sdk/gen-play-page.mts, do not edit. */
;(() => {

const PAD = { up:1, down:2, left:4, right:8, a:16, b:32, start:64, select:128 }
const KEYS = {
  ArrowUp:'up', ArrowDown:'down', ArrowLeft:'left', ArrowRight:'right',
  KeyW:'up', KeyS:'down', KeyA:'left', KeyD:'right',
  KeyZ:'a', KeyX:'b', Space:'a',
  Enter:'start', ShiftLeft:'select', ShiftRight:'select',
}

/* bridge.js reports upward through window.ReactNativeWebView.postMessage. In
 * the phone app that is the WebView bridge; here it is just this function. */
const listeners = []
window.ReactNativeWebView = {
  postMessage: (raw) => {
    let msg
    try { msg = JSON.parse(raw) } catch { return }
    for (const fn of listeners) fn(msg)
  },
}
const post = (msg) => window.__vuppBridge && window.__vuppBridge.receive(msg)

function status(text, bad) {
  const el = document.getElementById('status')
  if (!el) return
  el.textContent = text
  el.className = bad ? 'bad' : ''
}
function setName(title) {
  document.title = title ? title + ', Vupp' : 'Vupp'
  const el = document.getElementById('name')
  if (el) el.textContent = title || 'Vupp'
}

let started = false
listeners.push((msg) => {
  if (msg.type === 'ready') { started = true; onReady() }
  else if (msg.type === 'running') status('Playing ' + (msg.title || '') + ', arrows to move, Z and X for A and B')
  else if (msg.type === 'crash') status('It crashed in ' + msg.where + ': ' + msg.message, true)
  else if (msg.type === 'refused') status('The engine would not start it: ' + msg.reason, true)
})

/* --- input ----------------------------------------------------------------
 * The sim polls the pad every ~30ms, so a tap shorter than that is never
 * observed. Every release is held back to MIN_PRESS_MS, the same discipline the
 * phone app and the scripted playtest both apply. */
const MIN_PRESS_MS = 80
let mask = 0
const pressedAt = {}
const push = () => post({ type: 'pad', mask })

function down(button) {
  if (!button || (mask & PAD[button])) return
  pressedAt[button] = Date.now()
  mask |= PAD[button]
  push()
}
function up(button) {
  if (!button || !(mask & PAD[button])) return
  const clear = () => { mask &= ~PAD[button]; push() }
  const held = Date.now() - (pressedAt[button] || 0)
  if (held < MIN_PRESS_MS) setTimeout(clear, MIN_PRESS_MS - held)
  else clear()
}

addEventListener('keydown', (e) => {
  const b = KEYS[e.code]
  if (!b) return
  e.preventDefault()
  if (!e.repeat) down(b)
})
addEventListener('keyup', (e) => {
  const b = KEYS[e.code]
  if (!b) return
  e.preventDefault()
  up(b)
})
/* Leaving the tab mid-press would otherwise wedge a button down forever. */
addEventListener('blur', () => { if (mask) { mask = 0; push() } })

for (const el of document.querySelectorAll('[data-btn]')) {
  const b = el.dataset.btn
  const press = (e) => { e.preventDefault(); el.classList.add('on'); down(b) }
  const release = (e) => { e.preventDefault(); el.classList.remove('on'); up(b) }
  el.addEventListener('pointerdown', press)
  el.addEventListener('pointerup', release)
  el.addEventListener('pointercancel', release)
  el.addEventListener('pointerleave', release)
}

/* Touch on the screen itself, apps declaring the "touch" capability read this.
 * Coordinates are the 480x320 panel space the firmware expects. */
const screenCanvas = document.getElementById('canvas')
function panelXY(e) {
  const r = screenCanvas.getBoundingClientRect()
  return {
    x: Math.round(((e.clientX - r.left) / r.width) * 480),
    y: Math.round(((e.clientY - r.top) / r.height) * 320),
  }
}
screenCanvas.addEventListener('pointerdown', (e) => {
  const p = panelXY(e); post({ type: 'touch', x: p.x, y: p.y, down: true })
})
screenCanvas.addEventListener('pointermove', (e) => {
  if (e.buttons) { const p = panelXY(e); post({ type: 'touch', x: p.x, y: p.y, down: true }) }
})
addEventListener('pointerup', (e) => {
  const p = panelXY(e); post({ type: 'touch', x: p.x, y: p.y, down: false })
})

document.getElementById('restart').addEventListener('click', () => {
  post({ type: 'relaunch' }); status('Restarted')
})
document.getElementById('fresh').addEventListener('click', () => {
  post({ type: 'reset_store' }); post({ type: 'relaunch' })
  status('Started over with the saved progress cleared')
})


/* Minimal zip reader. The archive is written by fflate at level 6, so entries
 * are raw deflate or stored; DecompressionStream handles the former natively,
 * which keeps this page dependency-free. */
async function unzip(buffer) {
  const view = new DataView(buffer)
  const bytes = new Uint8Array(buffer)

  /* End of central directory: scan back for the signature, since the comment
   * field at the tail is variable length. */
  let eocd = -1
  for (let i = bytes.length - 22; i >= 0 && i > bytes.length - 65558; i--) {
    if (view.getUint32(i, true) === 0x06054b50) { eocd = i; break }
  }
  if (eocd < 0) throw new Error('That file is not a zip.')

  const count = view.getUint16(eocd + 10, true)
  let p = view.getUint32(eocd + 16, true)
  const out = {}
  const decoder = new TextDecoder()

  for (let i = 0; i < count; i++) {
    if (view.getUint32(p, true) !== 0x02014b50) throw new Error('That zip is damaged.')
    const method = view.getUint16(p + 10, true)
    const compressed = view.getUint32(p + 20, true)
    const nameLen = view.getUint16(p + 28, true)
    const extraLen = view.getUint16(p + 30, true)
    const commentLen = view.getUint16(p + 32, true)
    const localAt = view.getUint32(p + 42, true)
    const name = decoder.decode(bytes.subarray(p + 46, p + 46 + nameLen))
    p += 46 + nameLen + extraLen + commentLen

    /* The local header repeats the name and extra lengths, and they are NOT
     * always the same as the central directory's, the data starts after the
     * local copy. */
    const lNameLen = view.getUint16(localAt + 26, true)
    const lExtraLen = view.getUint16(localAt + 28, true)
    const start = localAt + 30 + lNameLen + lExtraLen
    const raw = bytes.subarray(start, start + compressed)

    if (name.endsWith('/')) continue
    let data
    if (method === 0) data = raw
    else if (method === 8) {
      const stream = new Blob([raw]).stream().pipeThrough(new DecompressionStream('deflate-raw'))
      data = new Uint8Array(await new Response(stream).arrayBuffer())
    } else throw new Error('That zip uses a compression this page cannot read.')
    out[name] = decoder.decode(data)
  }
  return out
}

/* Desktop zip tools wrap the contents in a folder named after it, so a game
 * zipped by hand arrives as "Frog Hop/app.json". Peel one common prefix, the
 * same forgiveness the phone app's importer applies, and the single most likely
 * way this fails in someone's hands otherwise. */
function unwrap(files) {
  const names = Object.keys(files).filter((n) => !n.startsWith('__MACOSX/') && !n.includes('/.'))
  if (!names.length) return files
  const slash = names[0].indexOf('/')
  if (slash < 0) return files
  const prefix = names[0].slice(0, slash + 1)
  if (!names.every((n) => n.startsWith(prefix))) return files
  const out = {}
  for (const n of names) out[n.slice(prefix.length)] = files[n]
  return out
}

const SOURCE = /^(app\.json|main\.lua|lib\/[A-Za-z0-9_-]+\.lua)$/
let pending = null

async function loadZip(file) {
  try {
    status('Opening ' + file.name + '...')
    const all = unwrap(await unzip(await file.arrayBuffer()))
    const files = {}
    for (const [name, body] of Object.entries(all)) if (SOURCE.test(name)) files[name] = body
    if (!files['app.json'] || !files['main.lua']) {
      throw new Error("That zip doesn't have a Vupp game in it.")
    }
    let title = 'Vupp'
    try { title = JSON.parse(files['app.json']).title || title } catch {}
    setName(title)
    document.getElementById('drop').classList.add('done')

    if (started) { status('Loading ' + title + '...'); post({ type: 'write_and_run', files }) }
    else { pending = files; status('Loading ' + title + '...') }
  } catch (err) {
    status(err.message || String(err), true)
  }
}

function onReady() {
  if (pending) { post({ type: 'write_and_run', files: pending }); pending = null }
  else status('Choose a game to play.')
}

const drop = document.getElementById('drop')
const input = document.getElementById('file')
document.getElementById('pick').addEventListener('click', () => input.click())
input.addEventListener('change', () => { if (input.files[0]) loadZip(input.files[0]) })
for (const type of ['dragenter', 'dragover']) {
  addEventListener(type, (e) => { e.preventDefault(); drop.classList.add('over') })
}
addEventListener('dragleave', () => drop.classList.remove('over'))
addEventListener('drop', (e) => {
  e.preventDefault()
  drop.classList.remove('over')
  const file = e.dataTransfer.files[0]
  if (file) loadZip(file)
})

})()
